/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Button: (typeof import('antd'))['Button']
  const Checkbox: (typeof import('antd'))['Checkbox']
  const Form: (typeof import('antd'))['Form']
  const Input: (typeof import('antd'))['Input']
}
