/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Card: (typeof import('antd'))['Card']
  const FooterToolbar: (typeof import('@ant-design/pro-components'))['FooterToolbar']
  const PageContainer: (typeof import('@ant-design/pro-components'))['PageContainer']
  const ProForm: (typeof import('@ant-design/pro-components'))['ProForm']
  const ProFormDateRangePicker: (typeof import('@ant-design/pro-components'))['ProFormDateRangePicker']
  const ProFormDigit: (typeof import('@ant-design/pro-components'))['ProFormDigit']
  const ProFormRadio: (typeof import('@ant-design/pro-components'))['ProFormRadio']
  const ProFormSelect: (typeof import('@ant-design/pro-components'))['ProFormSelect']
  const ProFormText: (typeof import('@ant-design/pro-components'))['ProFormText']
  const ProFormTextArea: (typeof import('@ant-design/pro-components'))['ProFormTextArea']
  const ProFormUploadButton: (typeof import('@ant-design/pro-components'))['ProFormUploadButton']
  const ProLayout: (typeof import('@ant-design/pro-components'))['ProLayout']
}
