name: Publish

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: read
  id-token: write

jobs:
  main:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.0.0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Print Environment Info
        run: npx nx report
        shell: bash
      - name: Build packages
        run: pnpm build:packages
        shell: bash
      - name: Publish packages
        run: pnpm release:publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
